version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}" ]
      interval: 10s
      retries: 5
      start_period: 5s
    networks:
      - safe_net

  backend:
    image: ghcr.io/nikcharge/backend:latest
    build:
      context: ./Backend
      dockerfile: Dockerfile.backend
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/admin"
      SPRING_DATASOURCE_USERNAME: "${POSTGRES_USER}"
      SPRING_DATASOURCE_PASSWORD: "${POSTGRES_PASSWORD}"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
      stripe.api.key: "${STRIPE_API_KEY}"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://backend:8080/actuator/health" ]
      interval: 30s
      retries: 3
      start_period: 10s
    networks:
      - safe_net

  frontend:
    image: ghcr.io/nikcharge/frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
      args:
        NODE_ENV: ${NODE_ENV}
        VITE_APP_API_BASE_URL: /api
    environment:
      - NODE_ENV=${NODE_ENV}
    volumes:
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - safe_net

  nginx:
    image: nginx:1.25
    container_name: nginx
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
    networks:
      - safe_net

volumes:
  postgres_data:
    driver: local

networks:
  safe_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.139.1.0/24
