# Usa uma imagem oficial do OpenJDK
FROM openjdk:21-jdk

# Define o argumento para o caminho do JAR
ARG JAR_FILE=target/*.jar

# Copia o JAR gerado para dentro do container
COPY target/Backend-0.0.1-SNAPSHOT.jar app.jar

# Expõe a porta do Spring Boot (necessária para o NGINX fazer proxy)
EXPOSE 8080

# Comando para executar a app e garantir que logs vão para o STDOUT
CMD ["sh", "-c", "java -jar /app.jar 2>&1 | tee /proc/1/fd/1"]
