name: Deploy

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  acceptance_tests:
    name: Acceptance Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin

      - name: Set up Firefox
        uses: browser-actions/setup-firefox@latest

      - name: Start Docker Compose Environment
        run: docker compose up -d
        working-directory: .

  build:
    name: Docker Build and Push
    needs: acceptance_tests
    runs-on: ubuntu-latest
    env:
      PRODUCTION: true

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Images
        uses: docker/bake-action@v3
        with:
          push: true
          files: docker-compose.yml
          workdir: .
          set: |
            *.cache-to=type=gha,scope=cached-stage,mode=max
            *.cache-from=type=gha,scope=cached-stage

  deploy:
    name: Deploy to UA VM
    needs: build
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy Application
        run: |
          docker compose -f docker-composeyml pull
          docker compose -f docker-compose.yml up -d --remove-orphans
          docker container prune -f
          docker image prune -af
          docker builder prune
