name: Deploy project

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Prepare .env file
        run: |
          if [ -f .env ]; then
            echo ".env file found, continuing."
          else
            echo ".env file not found!" && exit 1
          fi

      - name: Configure Nginx for deployment
        run: |
          cp nginx/nginx.conf nginx/nginx.conf  

      - name: Clean up unused Docker resources
        run: |
          docker compose down --remove-orphans --volumes
          docker system prune -af
          docker volume prune -f

      - name: Deploy with Docker Compose
        run: |
          docker compose -f docker-compose.yml up -d --build --remove-orphans
