name: Deploy project

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Prepare .env file
        run: |
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "NODE_ENV=development" >> .env
          echo "VITE_API_URL=/api" >> .env


      - name: Configure Nginx for deployment
        run: |
          cp nginx/nginx.conf

      - name: Clean up unused Docker resources
        run: |
          docker compose down --remove-orphans --volumes
          docker system prune -af
          docker volume prune -f

      - name: Deploy with Docker Compose
        run: |
          docker compose -f docker-compose.yml up -d --build --remove-orphans
