name: Deploy

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
    types: [opened, synchronize, reopened]
  workflow_dispatch:

env:
  GITHUB_REPOSITORY_OWNER: nikcharge

jobs:
  acceptance_tests:
    name: Acceptance Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin

      - name: Set up Firefox
        uses: browser-actions/setup-firefox@latest

      - name: Build with Maven
        run: mvn -f ./Backend/pom.xml clean package -DskipTests

      - name: Upload Backend Jar Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: backend-jar
          path: ./Backend/target/*.jar


      - name: Start Docker Compose Environment
        run: docker compose up -d
        env:
          GITHUB_REPOSITORY_OWNER: ${{ env.GITHUB_REPOSITORY_OWNER }}

  build:
    name: Docker Build and Push
    needs: acceptance_tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Backend Jar Artifact
        uses: actions/download-artifact@v3.1.3        
        with:
          name: backend-jar
          path: ./Backend/target

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Images
        run: |
          docker compose build
          docker compose push

  deploy:
    name: Deploy to UA VM
    needs: build
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy Application
        run: |
          docker compose -f docker-compose.yml pull
          docker compose -f docker-compose.yml up -d --remove-orphans
          docker container prune -f
          docker image prune -af
          docker builder prune
